### ISSUE TITLE
wiiurpxtool is generating broken rpx files.

### ISSUE THREAD

**Issue by Satoshi64** [0CBH0/wiiurpxtool#2]
Unpack a VC vessel.rpx and repack it again with the tool, console freezes.
Unpacking the rpx with this tool and repacking it with the SDK tool works.

Edit: Found something, the original rpx file has 04A0 at 0x462 and wiiurpxtool writes 04C0 on the new file. After restoring the value the rpx works again.

**Comment by 0CBH0** [comment]
The data at 0x462 is the position of the crc data, it's wrong because of the wrong argument of the function fseek... Thanks for your issue~(°∀°)ﾉ!
