### ISSUE TITLE
Generate a corrupt rpx output

### ISSUE THREAD

**Issue by cucholix** [0CBH0/wiiurpxtool#3]
Hi,
I'm using wiiurpxtool v1.2 and it generate a corrupted rpx when compressing it.
The rpx that I'm trying to edit is m2engage.rpx, the steps that reproduce the problem:
-Extract m2engage.rpx from Wii U GBA VC.
-Decrypt m2engage.rpx with wiiurpxtool v1.2 (no edit through hex editor)
-Encrypt the output
-When comparing the original rpx with the encryted one there are some difference in the first code blocks.
-If you edit m2engage decrypted (in my case I exchange one char) then encrypt it then the difference reach most of the code.

**Comment by 0CBH0** [comment]
Sorry for my missing. It may caused by my OCD... I just want to align the data to 0x40.
But I don't know whether the game woule be crashed with the alignment of crc data.
Anyway, I have changed it back... ( ´ ∀`)
