### ISSUE TITLE
Code ownership question

### ISSUE THREAD

**Issue by ghost** [0CBH0/wiiurpxtool#5]
Is this based on the leaked SDK program, or is it non-nintendo code? Just want to make sure before using it

**Comment by 0CBH0** [comment]
The codes are based on the source code of Hykem's rpl2elf.
Thus the names used in the structures and macro definitions have the source problem.
I find these names was defined firstly in the SDK of wii after researching the source of these names.
Therefore, the ownership of these names may be follow:
wiiurpxtool <- rpl2elf(Hykem, comex, deroad) <- rpltools* <- the format of ELF in the SDK of wii
*rpltools: dumprpl, makerpl etc. in the SDK of wiiu without source codes.

Other codes are non-nintendo code.
Thus you could use of the codes with different names of definition if there were some rights issues.
