### ISSUE TITLE
Cannot compress back main rpx of Splatoon

### ISSUE THREAD

**Issue by eadmaster** [0CBH0/wiiurpxtool#6]
the file is `Gambit.rpx` (crc32:E958CB86) from Splatoon AGMP01 (v1.0)

Decompression works fine, but compressing back does not
(the decompressed binary is just copied over).

This is the only one i've found by now..

**Comment by eadmaster** [comment]
fixed by updating to the [latest nx fork](https://github.com/yawut/wiiurpxtool-ng).

**Comment by 0CBH0** [comment]
I tested the Gambit.rpx (crc32:E958CB86), but the compression process is fine.
Actually, each process would copy the temporary file to the destination file.
Thus the error perhaps caused by the name or path of files?
I'm not sure...

**Comment by eadmaster** [comment]
the path was `R:\Gambit.rpx`.

I've also found another issue with the StarFoxZero main binary, which was decompressed partially...

**Comment by 0CBH0** [comment]
Do you have the offset of the section without decompressing?

**Comment by eadmaster** [comment]
> Do you have the offset of the section without decompressing?

no, sorry,i've deleted the files already.

Btw i was using [this old build from the releases section](https://github.com/0CBH0/wiiurpxtool/releases/download/v1.3/wiiurpxtool.zip), which could be the real cause...

**Comment by 0CBH0** [comment]
I get it, thanks for the feedback :)
