### ISSUE TITLE
[REQ] Ability to batch compress RPX's?

### ISSUE THREAD

**Issue by Ploggy** [0CBH0/wiiurpxtool#7]
Would it be possible to add the ability to compress multiple RPX files in a folder at once?
I've noticed Retroarch RPX files aren't compressed and are on the large side, I managed to compress a couple manually with your wiiurpxtool and it saves quite abit of space (the FBA2012 Cores shrinks down to 20MB from 60MB! 
But there's ALOT of RA Core RPX files :P and doing each file manually would be a pain, especially since the Cores are always being updated.
So the hope is you can add support for compressing multiple RPX files at once :)

Thank You.

**Comment by 0CBH0** [comment]
The function of batch processing may not be supported.
But you could process all rpx files recursively in batches by bat/shell script, such as:
save the follow bat script as "compress.bat" and run it on windows:
`@echo off`
`for /f "delims=" %%i in ('dir <top_dir>\*.rpx /s/b/a-d') do (wiiurpxtool -c "%%i")`
`pause`
or run the follow shell command directly on linux:
`find <top_dir> -name "*.rpx" | awk '{print "wiiurpxtool -c "$1 | "sh"}'`
(* change <top_dir> to your directory name)

**Comment by Ploggy** [comment]
Aha, That worked perfectly! Thank you.

Before Compression = 1.44GB
After Compression = 569MB !!

Is it ok if I post this on the GBAtemp WiiU RA thread?

**Comment by 0CBH0** [comment]
okay👍

**Comment by Ploggy** [comment]
Thanks mate :) nice one.
